# Generated by Django 4.2.16 on 2024-10-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_balancerequest_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RechargeRequest',
        ),
    ]
