# Generated by Django 4.2.16 on 2024-10-30 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_alter_seller_balance'),
        ('billing', '0004_delete_rechargerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancerequest',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balancerequests', to='sellers.seller'),
        ),
    ]
