# Generated by Django 4.2.16 on 2024-10-27 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='name',
        ),
        migrations.AddField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
