# Generated by Django 4.2.16 on 2024-10-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_remove_seller_name_seller_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=11),
        ),
    ]
