# Generated by Django 4.2.16 on 2024-10-27 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_balancerequest_amount_and_more'),
        ('transactions', '0002_transaction_description_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_transaction', to='billing.balancerequest'),
        ),
    ]
